import requests
from bs4 import BeautifulSoup
import json
import os
import uuid
from typing import List, Dict, Any

# Ensure the collected_data directory exists
os.makedirs("collected_data", exist_ok=True)

def scrape_clinical_trials():
    """Scrape clinical trial data from a public registry."""
    # This is a placeholder for a real scraping implementation.
    # In a real-world scenario, you would use a library like Selenium
    # to interact with a dynamic website and extract the data.
    print("Scraping clinical trial data...")
    # For demonstration purposes, we'll use a static list of sample data.
    sample_data = [
        {
            "steps": "1. Recruit patients\n2. Obtain informed consent\n3. Administer treatment\n4. Monitor patients\n5. Collect data\n6. Analyze results",
            "roles": "Principal Investigator, Clinical Research Coordinator, Nurse, Data Manager",
            "notes": "Follow all applicable regulations and guidelines."
        },
        {
            "steps": "1. Screen subjects\n2. Randomize subjects\n3. Administer drug or placebo\n4. Follow up with subjects\n5. Record adverse events\n6. Unblind study",
            "roles": "Investigator, Study Coordinator, Pharmacist, Statistician",
            "notes": "Ensure proper documentation of all study activities."
        }
    ]
    return sample_data

def scrape_scientific_procedures():
    """Scrape scientific procedure data from a public source."""
    # This is a placeholder for a real scraping implementation.
    print("Scraping scientific procedure data...")
    # For demonstration purposes, we'll use a static list of sample data.
    sample_data = [
        {
            "steps": "1. Prepare reagents\n2. Perform experiment\n3. Collect data\n4. Analyze data\n5. Write report",
            "roles": "Scientist, Research Assistant, Lab Manager",
            "notes": "Use appropriate personal protective equipment."
        },
        {
            "steps": "1. Culture cells\n2. Treat cells with compound\n3. Lyse cells\n4. Perform western blot\n5. Analyze results",
            "roles": "Biologist, Lab Technician, Principal Investigator",
            "notes": "Follow sterile technique to prevent contamination."
        }
    ]
    return sample_data

def generate_training_examples() -> List[Dict[str, Any]]:
    """Generate training examples from scraped data."""
    training_data = []
    
    # Scrape data from various sources
    clinical_trial_data = scrape_clinical_trials()
    scientific_procedure_data = scrape_scientific_procedures()
    
    # Combine the scraped data
    all_data = clinical_trial_data + scientific_procedure_data
    
    # Create training examples
    for item in all_data:
        # Determine document type
        doc_type = "sop" if "procedure" in item.get("notes", "").lower() else "batch"
        
        # Create training example
        example = {
            "input": {
                "type": doc_type,
                "steps": item["steps"],
                "roles": item["roles"],
                "notes": item["notes"]
            },
            "output": "",  # The output will be generated by the model
            "feedback_score": 5.0  # High quality examples for training
        }
        
        training_data.append(example)
    
    return training_data

def save_training_data(training_data: List[Dict[str, Any]]) -> None:
    """Save training data to file."""
    for example in training_data:
        # Create a unique ID for each document
        doc_id = f"doc_{uuid.uuid4()}"
        doc_path = os.path.join("collected_data", f"{doc_id}.json")
        
        # Format the document data
        doc_data = {
            "input": example["input"],
            "generated_content": example["output"],
            "doc_type": example["input"]["type"],
            "metadata": {
                "model_version": "v1",
                "template_type": "web_scraped",
                "timestamp": "2025-07-19T12:00:00"
            },
            "feedback": {
                "score": example["feedback_score"],
                "text": "Generated from web-scraped data"
            }
        }
        
        # Save the document
        with open(doc_path, "w") as f:
            json.dump(doc_data, f, indent=2)

if __name__ == "__main__":
    print("Generating training data from web-scraped sources...")
    training_data = generate_training_examples()
    save_training_data(training_data)
    print(f"Generated {len(training_data)} training examples.")
    print("Individual examples saved to collected_data/ directory")
