#!/usr/bin/env bash
#
# One-command production deploy for SmartSOP on a single Docker host
# (a cloud VM or an on-prem box). Idempotent — re-run it to deploy updates.
#
#   DOMAIN=sop.your-facility.com ACME_EMAIL=you@your-facility.com ./deploy.sh
#
# What it does:
#   1. Checks Docker + the compose plugin are present (offers to install on Ubuntu/Debian).
#   2. Creates .env on first run (random JWT_SECRET, your DOMAIN, HTTPS CORS).
#   3. Builds and starts the full stack behind Caddy (automatic HTTPS).
#   4. Pulls the Ollama model (skip with WITHOUT_OLLAMA=1).
#
set -euo pipefail
cd "$(dirname "$0")"

RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'; NC='\033[0m'
info() { printf "${GRN}==>${NC} %s\n" "$1"; }
warn() { printf "${YLW}!! ${NC} %s\n" "$1"; }
die()  { printf "${RED}xx ${NC} %s\n" "$1" >&2; exit 1; }

OLLAMA_MODEL="${OLLAMA_MODEL:-llama3}"

# ── 1. Docker ───────────────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  if [ -f /etc/debian_version ] && [ "$(id -u)" = "0" ]; then
    info "Installing Docker…"
    curl -fsSL https://get.docker.com | sh
  else
    die "Docker is not installed. Install it first: https://docs.docker.com/engine/install/"
  fi
fi
docker compose version >/dev/null 2>&1 || die "The Docker Compose plugin is required (docker compose)."

# ── 2. .env ─────────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  info "Creating .env (first run)…"
  : "${DOMAIN:?Set DOMAIN, e.g. DOMAIN=sop.your-facility.com ./deploy.sh}"
  ACME_EMAIL="${ACME_EMAIL:-admin@${DOMAIN}}"
  JWT_SECRET="$(docker run --rm python:3.12-alpine python -c 'import secrets;print(secrets.token_urlsafe(48))' 2>/dev/null \
                || head -c 48 /dev/urandom | base64 | tr -d '/+=' | cut -c1-64)"
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_ENV=production
FLASK_ENV=production
AUTO_CREATE_TABLES=false

DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}

# Signing secret — keep this safe; rotating it logs everyone out.
JWT_SECRET=${JWT_SECRET}

# The desktop clients / browsers connect over HTTPS at your domain.
CORS_ORIGINS=https://${DOMAIN}
EOF
  chmod 600 .env
  info "Wrote .env (DOMAIN=${DOMAIN}). Keep JWT_SECRET secret."
else
  info "Using existing .env"
  grep -q '^DOMAIN=' .env || die ".env exists but has no DOMAIN= line. Add DOMAIN and CORS_ORIGINS, then re-run."
fi

# shellcheck disable=SC1091
set -a; . ./.env; set +a
[ -n "${JWT_SECRET:-}" ] || die "JWT_SECRET is empty in .env."

# ── 3. Build & start ────────────────────────────────────────────────────────
COMPOSE=(docker compose -f docker-compose.yml -f docker-compose.prod.yml)

SCALE=()
if [ "${WITHOUT_OLLAMA:-0}" = "1" ]; then
  warn "WITHOUT_OLLAMA=1 — AI-assist features will be unavailable (the app degrades gracefully)."
  SCALE=(--scale ollama=0)
fi

info "Building and starting the stack (this can take a few minutes on first run)…"
"${COMPOSE[@]}" up -d --build "${SCALE[@]}"

# ── 4. Ollama model ─────────────────────────────────────────────────────────
if [ "${WITHOUT_OLLAMA:-0}" != "1" ]; then
  info "Pulling the Ollama model (${OLLAMA_MODEL})… (first time only)"
  "${COMPOSE[@]}" exec -T ollama ollama pull "${OLLAMA_MODEL}" || \
    warn "Could not pull ${OLLAMA_MODEL} now — run: ${COMPOSE[*]} exec ollama ollama pull ${OLLAMA_MODEL}"
fi

info "Done. SmartSOP is starting at: https://${DOMAIN}"
echo
echo "  • First HTTPS request may take ~30s while Caddy obtains the certificate."
echo "  • Point the desktop app at: https://${DOMAIN}"
echo "  • Logs:    ${COMPOSE[*]} logs -f"
echo "  • Update:  git pull && ./deploy.sh"
echo "  • Stop:    ${COMPOSE[*]} down"
