"""add sop lifecycle fields and signoffs

Revision ID: 2eead6437d1f
Revises: 64b472838920
Create Date: 2026-07-21 14:17:03.400722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eead6437d1f'
down_revision = '64b472838920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_signoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('meaning', sa.String(length=300), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('signed_by', sa.String(length=255), nullable=True),
    sa.Column('signed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sop_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('effective_date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('review_date', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('supersedes_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_column('supersedes_id')
        batch_op.drop_column('review_date')
        batch_op.drop_column('effective_date')
        batch_op.drop_column('department')
        batch_op.drop_column('sop_number')
        batch_op.drop_column('protocol_type')

    op.drop_table('protocol_signoffs')
    # ### end Alembic commands ###
