"""add document approval audit fields

Revision ID: 860d4358bf8b
Revises: 05ce6b7205a0
Create Date: 2026-06-23 23:57:33.725533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860d4358bf8b'
down_revision = '05ce6b7205a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
