"""add step branch json

Revision ID: a37479d1fb5d
Revises: d53aa8c2ebb2
Create Date: 2026-07-21 16:20:48.367248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37479d1fb5d'
down_revision = 'd53aa8c2ebb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_run_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_json', sa.Text(), nullable=True))

    with op.batch_alter_table('protocol_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_steps', schema=None) as batch_op:
        batch_op.drop_column('branch_json')

    with op.batch_alter_table('protocol_run_steps', schema=None) as batch_op:
        batch_op.drop_column('branch_json')

    # ### end Alembic commands ###
