"""add typed step components

Revision ID: d53aa8c2ebb2
Revises: 2eead6437d1f
Create Date: 2026-07-21 16:06:47.680369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53aa8c2ebb2'
down_revision = '2eead6437d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_run_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('components_json', sa.Text(), nullable=True))

    with op.batch_alter_table('protocol_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('components_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocol_steps', schema=None) as batch_op:
        batch_op.drop_column('components_json')

    with op.batch_alter_table('protocol_run_steps', schema=None) as batch_op:
        batch_op.drop_column('components_json')

    # ### end Alembic commands ###
